// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-tIohxCyBg6rtHzxsVoDRkUwWG11-vm8',
    appId: '1:1018216232414:web:41d5b9ef8f68ec6850594f',
    messagingSenderId: '1018216232414',
    projectId: 'dealdive-e7d2b',
    authDomain: 'dealdive-e7d2b.firebaseapp.com',
    storageBucket: 'dealdive-e7d2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAKXuvQVBB5Xj4t9DOai-Mv4_oGs7xo5Q',
    appId: '1:1018216232414:android:b2fe4b9a786bb3de50594f',
    messagingSenderId: '1018216232414',
    projectId: 'dealdive-e7d2b',
    storageBucket: 'dealdive-e7d2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVhJvfwgnkCpMe-PiKgLZzW82cTVuFjn0',
    appId: '1:1018216232414:ios:955113defa62845750594f',
    messagingSenderId: '1018216232414',
    projectId: 'dealdive-e7d2b',
    storageBucket: 'dealdive-e7d2b.firebasestorage.app',
    iosBundleId: 'com.example.dealdiveCleanNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVhJvfwgnkCpMe-PiKgLZzW82cTVuFjn0',
    appId: '1:1018216232414:ios:955113defa62845750594f',
    messagingSenderId: '1018216232414',
    projectId: 'dealdive-e7d2b',
    storageBucket: 'dealdive-e7d2b.firebasestorage.app',
    iosBundleId: 'com.example.dealdiveCleanNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBJ-njZrwrqb8LqTt4aN8NYyCNNqBIpvk',
    appId: '1:1018216232414:web:534c223ce75953a250594f',
    messagingSenderId: '1018216232414',
    projectId: 'dealdive-e7d2b',
    authDomain: 'dealdive-e7d2b.firebaseapp.com',
    storageBucket: 'dealdive-e7d2b.firebasestorage.app',
  );
}